
   datasource:
     driver-class-name: com.mysql.jdbc.Driver
     username: root
     password: password
     url: jdbc:mysql://localhost:3306/order?useUnicode=true&characterEncoding=utf8       # 数据库名称





 logging:
   level:
     com.gsw.mapper: debug

